### PR TITLE
Move to newest Jest version & TypeScript

### PR DESCRIPTION
**Pull request by rene-leanix**
This is a test-branch to check if testdouble-jest can be run with TypeScript (and the newest version of Jest).

### CODE REVIEW

**Comment by searls** [comment]
I don't understand -- did you intend for this to be a PR against the main repo?

**Comment by rene-leanix** [comment]
No, sorry, this was merely intended as a show case for #7. That's why I created this as a draft PR, but would have been better to create the PR just for my fork. Will close it now.

**Comment by RA80533** [comment]
Use `import { default as td }` (or, since you have `esModuleInterop` enabled, `import td`) instead of `import * as td`, @rene-leanix. `td` will be an entirely different shape for the wildcard import—imagine it as a collection of all the exports from the module, including a default export (which is what you actually want).

Just out of curiosity, does Jest not work for your use case? It has built-in mocking, etc.

**Comment by rene-leanix** [comment]
To answer your question, @RA80533, we ended up using Jest's own mocking and [jest-when](https://www.npmjs.com/package/jest-when) (with a small addition of our own to create mock return values). Here's some example code:

```ts
jest.enableAutomock();
jest.unmock('@app/spec/mocks'); // file with`when()` and other test-helpers
jest.unmock('@app/helpers'); // file to be tested

//... imports

afterAll(() => {
  jest.disableAutomock();
  cleanupWhenMocks();
});

describe('getTimeSpan()', () => {
  it('returns correct timespan based on expected function calls', () => {
    const zoomLevel = mock<TimeUnit>();
    const today = when(startOfYear).calledWith(expect.any(Date)).mockReturnValueOnce();
    const minus10Years = when(addUnits).calledWith(today, 'year', -10).mockReturnValueOnce();
    const plus10Years = when(addUnits).calledWith(today, 'year', 10).mockReturnValueOnce();
    const begin = when(getBeginOfUnit).calledWith(minus10Years, zoomLevel).mockReturnValueOnce();
    const end = when(startOfNextUnit).calledWith(plus10Years, zoomLevel).mockReturnValueOnce();

    const timespan = getTimeSpan(zoomLevel);

    expect(timespan).toStrictEqual({ unit: zoomLevel, begin, end });
  });
});
```

All variables in this example are mocked with a simple `mock()`-function that returns an otherwise object with a unique identifier. That simplifies the test a lot and makes look like the actual code a lot when it comes to function calls.

**Pull request closed without merging**
